baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tianyu Shi"

[params]
  description = "A website built with Hugo"
  author = "Your Name"
  email = "example@example.com"
  shortbio = "A short biography"
  officeAddress = "Your Office Address"
  officeMapLink = "https://maps.google.com"
  PGPPubkeyLink = "#"
  PGPFingerprint = "0123456789ABCDEF"
  ShowPGP = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2 